version: '3'

volumes:
  media-store:


services: 

  traefik:
    image: "traefik"
    restart: always
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  synapse:
    image: matrixdotorg/synapse:latest
    restart: unless-stopped
    environment:
      - SYNAPSE_CONFIG_PATH=/etc/homeserver.yaml
    volumes:
      - ./matrix-config/homeserver.yaml:/etc/homeserver.yaml
      - ./matrix-config/my.matrix.host.signing.key:/etc/synapsetest.signing.key
      - ./matrix-config/synapse.log:/synapse.log
      - ./files:/data
      - media-store:/media_store
    depends_on:
      - db
    labels:
      - traefik.enable=true
      - traefik.http.routers.synapse.entryPoints=web
      - traefik.http.routers.synapse.rule=Host(`matrix.local`)


      
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD=synapse
      - POSTGRES_DB=synapse
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    ports:
      - "5432:5432"
    volumes:
      - ./schemas:/var/lib/postgresql/data

  riot:
    image: bubuntux/riot-web
    container_name: riot
    restart: unless-stopped
    depends_on:
      - synapse
    labels:
      - traefik.enable=true
      - traefik.http.routers.riot.entryPoints=web
      - traefik.http.routers.riot.rule=Host(`chat.local`)
